--- #YAML:1.0
name:               Mojolicious-Plugin-FormFields
version:            0.03
abstract:           Use objects and data structures in your forms
author:
    - Skye Shaw <skye.shaw AT gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mojolicious:          4.50
    Mojolicious::Plugin::ParamExpand:  0
resources:
    bugtracker:  http://github.com/sshaw/Mojolicious-Plugin-FormFields/issues
    homepage:    http://github.com/sshaw/Mojolicious-Plugin-FormFields
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
